### ISSUE TITLE
Seg fault when running example

### ISSUE THREAD

**Issue by SethPoulsen** [vbarrielle/phototex#1]
Just happened upon your project, looks cool! I was just thinking of building something similar myself. 

after running `cargo build`, when I try to run `phototex`, I'm getting the following error: 

```sh
~/git/phototex/example$ ../target/debug/phototex source_images -o latex_album --title "Beautiful Places" --title-image-name 2016-08-09_12-39-40.jpg
thread '<unnamed>' panicked at 'attempted to leave type `nodrop::NoDrop<(epoch::Epoch, garbage::Bag)>` uninitialized, which is invalid', /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/mem/mod.rs:660:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Segmentation fault

```

**Comment by vbarrielle** [comment]
Hello, thank you for reporting this issue.

Apparently this was caused by the used version of crossbeam being incompatible with the latest rustc. I've updated the dependencies and pushed to master, which should resolve the issue (it did for me).

**Comment by SethPoulsen** [comment]
Seems to work now. Thanks!
